version: '2'

services:
  eps-db:
    container_name: eps-db
    image: fzicell/eps-db
    hostname: eps-db
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
    volumes:
      - ./eps-db/shared:/docker-entrypoint-initdb.d
    working_dir: /opt/shared
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      network:
        ipv4_address: 172.18.0.3

  eps-backend:
    container_name: eps-backend
    image: fzicell/eps-backend
    hostname: eps-backend
    volumes:
      - ./eps-backend/shared:/opt/shared
    working_dir: /opt/shared
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8080:8080"
    expose:
      - "9000"
      - "9001"
      - "8080"
    links:
      - eps-db
    networks:
      network:
        ipv4_address: 172.18.0.5

networks:
  network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
