FROM mysql/mysql-server

MAINTAINER zoltan.ferenczik@icell.hu

LABEL Description="This image is used to start RestAPI for testing and demonstration purposes" Vendor="iCell Mobilsoft" Version="1.0"

ENV DEBIAN_FRONTEND noninteractive

EXPOSE 3306 33060

#Commands

#CMD ["mysqld"]
#COPY /opt/shared/init-tables.sql /docker-entrypoint-initdb.d/

